package:
  name: pyevtk
  version: "1.0.0"

source:
  fn: PyEVTK-1.0.0.tar.gz
  url: https://pypi.python.org/packages/6b/92/d2ce84a10c6a4ac31620d50c0accd88a2f467ca08f4bcb5f665d2f92bb10/PyEVTK-1.0.0.tar.gz
  md5: f19b0ef543a271c56f4ade3987d514e7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyevtk = pyevtk:main
    #
    # Would create an entry point called pyevtk that calls pyevtk.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy >=1.8.0

  run:
    - python
    - numpy >=1.8.0

test:
  # Python imports
  imports:
    - pyevtk

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pypi.python.org/pypi/PyEVTK
  license: UNKNOWN
  summary: 'Export data as binary VTK files'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
